# Generated by Django 3.1 on 2021-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.IntegerField(default=0)),
                ('mp', models.IntegerField(default=0)),
                ('job', models.IntegerField(choices=[(1, '勇者'), (2, '魔法使い'), (3, '戦士'), (4, '賢者'), (5, '遊び人')])),
                ('birthday', models.DateField()),
            ],
        ),
    ]
